<?php
// ==== RecipeHub: Database & Helpers (Auto-Backup Enabled) ====
if (session_status() === PHP_SESSION_NONE) { session_start(); }

$DB_HOST = getenv('DB_HOST') ?: 'localhost';
$DB_USER = getenv('DB_USER') ?: 'root';
$DB_PASS = getenv('DB_PASS') ?: '';
$DB_NAME = getenv('DB_NAME') ?: 'recipehub';

$mysqli = @new mysqli($DB_HOST, $DB_USER, $DB_PASS, $DB_NAME);
if ($mysqli->connect_errno) { die("Database connection failed: " . $mysqli->connect_error); }
$mysqli->set_charset('utf8mb4');

function clean($s){ global $mysqli; return $mysqli->real_escape_string(trim($s)); }
function isLoggedIn(){ return isset($_SESSION['user']); }
function currentUser(){ return $_SESSION['user'] ?? null; }
function isAdmin(){ return isset($_SESSION['user']) && ($_SESSION['user']['email'] === 'admin@recipehub.local'); }

$uploadsDir = __DIR__ . '/uploads';
if (!is_dir($uploadsDir)) { @mkdir($uploadsDir, 0775, true); }

$sqlDir = __DIR__ . '/sql';
if (!is_dir($sqlDir)) { @mkdir($sqlDir, 0775, true); }

// Auto tables (safe to re-run)
$mysqli->query("CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

$mysqli->query("CREATE TABLE IF NOT EXISTS recipes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  category VARCHAR(50) DEFAULT 'General',
  ingredients TEXT NOT NULL,
  steps TEXT NOT NULL,
  image VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

function csrf_token() {
  if (empty($_SESSION['csrf'])) { $_SESSION['csrf'] = bin2hex(random_bytes(16)); }
  return $_SESSION['csrf'];
}
function csrf_check() {
  if (!isset($_POST['csrf']) || !isset($_SESSION['csrf']) || !hash_equals($_SESSION['csrf'], $_POST['csrf'])) {
    die('Invalid CSRF token');
  }
  return null;
}

// ---- Auto-Backup: export recipes table to sql/recipes_data.sql ----
function exportRecipes(){
  global $mysqli;
  $res = $mysqli->query("SELECT id,user_id,title,category,ingredients,steps,image,created_at FROM recipes ORDER BY id");
  if(!$res){ return; }

  $lines = [];
  $lines[] = "-- Auto-generated by RecipeHub (do not edit)";
  $lines[] = "SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';";
  $lines[] = "SET time_zone = '+00:00';\n";
  $lines[] = "USE `recipehub`;\n";
  $lines[] = "-- Purge then insert fresh data";
  $lines[] = "TRUNCATE TABLE `recipes`;";
  while($row = $res->fetch_assoc()){
    $id = (int)$row['id'];
    $user_id = (int)$row['user_id'];
    $title = $mysqli->real_escape_string($row['title']);
    $category = $mysqli->real_escape_string($row['category']);
    $ingredients = $mysqli->real_escape_string($row['ingredients']);
    $steps = $mysqli->real_escape_string($row['steps']);
    $image = isset($row['image']) && $row['image']!=='' ? "'".$mysqli->real_escape_string($row['image'])."'" : "NULL";
    $created = $mysqli->real_escape_string($row['created_at']);

    $sql = "INSERT INTO `recipes` (`id`,`user_id`,`title`,`category`,`ingredients`,`steps`,`image`,`created_at`) VALUES ";
    $sql .= "($id,$user_id,'$title','$category','$ingredients','$steps',$image,'$created');";
    $lines[] = $sql;
  }
  $out = implode("\n", $lines) . "\n";
  file_put_contents(__DIR__ . "/sql/recipes_data.sql", $out);
}
?>